language: node_js
node_js: '7'
cache: npm
before_script:
  -  psql -c 'create database choredb-dev_test;' -U postgres
install:
- npm install
deploy:
  provider: heroku
  api_key:
    secure: UaH4BoSn5p4kVO8ci+rwbbE6NgWkOr11OynUI2GWuk8+DtBIq3kfUAj/e11jATJRNr9wY6nEaN7Vx1+rGJqBIb0wr2wjOmA5Ui8MR2K9RZlZ+xwZg2Z7Sb4O/3hynOJSFTzlis16ff3vl6lmfTMlJj0/UvpgqXQ6OTb3KRL5l6Kjn9JqYUGKCGSL2nKAAsJRnXlC8UE9YWRebClisoJ0jOFqZ6oz552WqWj1dWsRc93phG5OdmNyRpjgnfL22wikJbPANfHKfzlefwKXSosayNXtHe4WNEqVPhOUR8ciluJNfcj0KO/1YN6ULqz4EId5UbpvPzwRo5FXd0m3LAMmoTLspFMwwKNSQMr/groi5TeCNf2Np0wnFNdrgtmFtljsHwuyIEWvsXPa5FP1R7NyCyViOpxHnqBb5PqQt8TWrMMwB2AZ5R32i08XwaarlREtcfopxLVLFRF9EJKu7MoDLQH/g6HkFyBQHnQvXWtvuxh0kZ1f1Aya9kafPn8AfRXSGlcfcmh+axM7fjbaXlIaWBon4faIkZv6t9lD93VpuyJfAi4f95FitaGNGwnFzJeSZn/6mINcZVdmZkqEoudpccLbouPVuggTgVkWPElYMSaVVuTIyaGIUDe4prgyLvNv6ReJWHk2/DCmPYZ5Cs2HU3DOaA0+pDzPuNLlxXJKARM=
  app: choredb-api
  on:
    repo: ilarinie/node-choredb-2
